#!/bin/sh

[ $# -eq 1 ] || { echo 1>&2 "Usage: $0 TESTNAME" ; exit -1 ; }

export PATH="../../bunny:$PATH"
IN_DIR='in'
OUT_DIR='out'
EXEC='exec'

# Run
cd $1 || { echo 1>&2 "No such test" ; exit -2 ; }
CMD="bunny-main -i $IN_DIR -o $OUT_DIR ./$EXEC"
echo "PWD: $PWD"
echo "Running: '$CMD'"
$CMD

